services:
  db:
    image: "nsdigirolamo/tyche:db"
    container_name: "tyche-db"
    environment:
      POSTGRES_USER_FILE: /run/secrets/postgres_user_file
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_password_file
    secrets:
      - postgres_user_file
      - postgres_password_file
    volumes:
      - postgres-volume:/var/lib/postgresql/data
  api:
    image: "nsdigirolamo/tyche:api"
    container_name: "tyche-api"
    ports:
      - "8000:8000"
    environment:
      ENVIRONMENT_TYPE: production
      ALLOWED_ORIGIN: http://www.tyche.social
      DATABASE_URL_FILE: /run/secrets/database_url_file
      JWT_SECRET_FILE: /run/secrets/jwt_secret_file
    secrets:
      - database_url_file
      - jwt_secret_file
  app:
    image: "nsdigirolamo/tyche:app"
    container_name: "tyche-app"
    ports:
      - "80:80"
    environment:
      NODE_ENV: production

secrets:
  postgres_user_file:
    file: postgres_user.txt
  postgres_password_file:
    file: postgres_password.txt
  database_url_file:
    file: database_url.txt
  jwt_secret_file:
    file: jwt_secret.txt

volumes:
  postgres-volume:
